### PR TITLE
Template riak.conf. Only restart service if config changed

### PR DESCRIPTION
**Pull request by TJC**
This is a first pass at switching over to using a template to build riak.conf, and only restarting riak if the configuration changes.

### CODE REVIEW

**Comment by jsmartin** [comment]
Looks good (not tested).

**Comment by christophermancini** [comment]
This looks really good, my only thoughts are that it does not allow support for config options that are not already defined in the conf template file. An example of this is multi_backend or tls conf options and it would be unrealistic to setup each conf option in the template file.

@TJC @jsmartin The way our cuttlefish conf parser works, is last write wins, so I think a dictionary (like the original riak_conf) could be used with a for loop at the end of the template. What do you think?

**Comment by jsmartin** [comment]
My question is -- why does the template need the ability to loop through all the settings?  In roles/riak/defaults/main.yml set the role  default of:

    riak_conf_template: riak.conf.j2

Modify the task as such:

    - template: src={{ riak_conf_template }} dest=/etc/riak/riak.conf owner=root group=root mode=0444

A customer could override the path to a different template that they wanted to use by declaring it as inventory variable, or a parameter to the role.  For instance, in group_vars/all

    riak_conf_template: "{{ playbook_dir }}/templates/mycustom_riak_conf.j2"


Now they can edit it to their hearts content.  The goal of this role should be able to get something up and running, and still provide the ability for the customer to edit to their hearts content, while keeping the logic and maintenance of the role to a minimum.

**Comment by christophermancini** [comment]
That is an excellent solution, thanks for suggesting it. I will try to implement it this week.

**Comment by TJC** [comment]
I support jsmartin's suggestion, out of the two given. The dictionary lookup/replace system used previously is unusual and I think would confuse a lot of people.

There's a third way, too. You can say that files are built out of multiple fragments - thus you could have the custom extra options taken from another file and appended.

Thinking about the options though.. I think your suggestion of changing the template variable is pretty good. I'd go with that.

**Pull request merged**
