### PR TITLE
[fix] use custom http endpoints for riak commands

### PR DESCRIPTION
**Pull request by pmarques**
I'm starting using Ansible for some of my tasks and so I'm not very experienced with it. I lost several time looking for timeouts when running this role with custom configurations and as far as I could "debug" when you do it, changing settings like host and port require to also set http_conn parameter to riak module otherwise it will try to connect to the default host and port...

### CODE REVIEW

**Comment by mjbrender** [comment]
Hey @pmarques - excuse the huge delay here. We're working on cleaning up this code base and you'll see some major strides around the corner. I just want to check: is this customization optional or required?  If optional, we can merge with less worry.

Thanks for your patience and contribution!

**Comment by pmarques** [comment]
Hey @mjbrender I just updated the pull request text... sorry for the bad description!

In my tests I was using a custom bind interfaces/IPs + ports because some of them are in use. I also want to use a specific interface for riak. As far as I can see the ansible module sends commands to '127.0.0.1' and 8098, like ping and wait for kv.
I'm not sure right know if I should use the variable * riak_ip_addr*, because as far as can I remember the the problem started since I set *riak_http_bind_ip*. Maybe we should wait for the updates that you are talking about.

**Comment by mjbrender** [comment]
Great @pmarques - no problem at all! Let's keep this issue in Ready state and wait until someone can volunteer to review its impact & test.

**Comment by mjbrender** [comment]
Accepting this PR on develop despite the heavy work done on the 2.x branches. FYI to @pmarques that 2.x branch is the go-foward code. FYI to @christophermancini that this merge should be considered as we update master from 2.x branches.

**Pull request merged**
