### PR TITLE
Conditionally bypass systemd reload

### PR DESCRIPTION
**Pull request by lucafavatella**
Depends on #78

Related to #70

See also https://github.com/basho-labs/ansible-riak/pull/71/files#diff-55995e97bbcfe9b8fafbbd5e0fe7e066R66

### CODE REVIEW

**Comment by lucafavatella** [comment]
Travis CI error:
```
TASK [ansible-riak : install riak_shell.config with templated configuration] ***

fatal: [riak-test]: FAILED! => {"failed": true, "msg": "The conditional check 'riak_package == \"riak-ts\" and riak_shell_nodes is defined' failed. The error was: error while evaluating conditional (riak_package == \"riak-ts\" and riak_shell_nodes is defined): {{ riak_shell_nodes_list.split() }}: {% for host in groups[riak_shell_group] %}riak@{{ hostvars[host][riak_shell_interface]['ipv4']['address'] }} {% endfor %}: 'dict object' has no attribute u'riak'\n\nThe error appears to have been in '/home/travis/build/basho-labs/ansible-riak/tasks/main.yml': line 40, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: install riak_shell.config with templated configuration\n  ^ here\n"}
```

**Comment by lucafavatella** [comment]
> Travis CI error:

Issue is not caused by this PR - see #77

**Comment by christophermancini** [comment]
Can you perform a rebase and git force push to remove the commit that was handled via the other PR?

**Comment by lucafavatella** [comment]
> Can you perform a rebase and git force push to remove the commit that was handled via the other PR?

1 minute.

**Comment by lucafavatella** [comment]
> Can you perform a rebase and git force push to remove the commit that was handled via the other PR?

Done.

**Pull request merged**
