### PR TITLE
Dev 2.x

### PR DESCRIPTION
**Pull request by christophermancini**
Rewrite to support Riak 2+ features, packagecloud, and the latest releases from Debian and RHEL based Linux OSs.

### CODE REVIEW

**Comment by christophermancini** [comment]
@TJC and @jsmartin if you guys would be willing to give this PR a quick glance and maybe test it on your favorite linux distro, I would greatly appreciate it. I am using it on Cent7 and it is working well. Once all looks good, I will merge it and get it back up in Ansible Galaxy.

**Comment by mjbrender** [comment]
Worth noting to @basho-labs/ansible-committers as a collective. Great stuff @christophermancini!!

**Comment by javajolt** [comment]
We should probably refresh the README.md in this PR, too, to remove the comments about dev-2.x coming and update any version-specific info.

**Comment by mjbrender** [comment]
@javajolt good call. I'll make sure the README is good if you help make sure the code does the trick :+1:

**Comment by jsmartin** [comment]
At a glance:

1. The tasks in security.yml (creating users, etc) aren't idempotent.  They are just running commands.  That's going to result in a "changed" every time.
2. I can't say that I'm a big fan of downloading and running a shell script to setup the repo.
3. The disk tuning will be lost if the machine is rebooted.

Not any of those are blockers, but just an FYI.

**Comment by mjbrender** [comment]
Thanks @jsmartin - appreciate the notes.

**Comment by TJC** [comment]
I'm not a fan of the download-and-run-script either. Compare against this method:
Note that this way also avoids running apt-get update unless you need it to be run, so you get much faster repeated runs.

repo.yml
```
- name: install ES apt key
  copy: src=elasticsearch.gpg dest=/etc/apt/trusted.gpg.d/elasticsearch.gpg

- name: add ES apt repo
  copy: src=elasticsearch.list dest=/etc/apt/sources.list.d/elasticsearch.list
  notify: apt-get update

- name: flush riak-cs-repo handlers to get apt-get update run if required
  meta: flush_handlers
```

main.yml
```
- name: setup elasticsearch repo
  include: repo.yml
  creates: /etc/apt/sources.list.d/elasticsearch.list

- name: install elasticsearch package
  apt: name=elasticsearch state=installed

```

**Comment by jsmartin** [comment]
@TJC not really necessary to have the `include` and creates block.

Better off using http://docs.ansible.com/ansible/apt_repository_module.html (which will update the cache if repo has changed) to update/install the repository.

Also I'd use the apt_key module for adding the apt key: http://docs.ansible.com/ansible/apt_key_module.html.

**Comment by TJC** [comment]
I'm sure there was a reason I switched away from those, actually.. Sorry, I can't recall the exact issue now, though.

Although for the apt key I think it was because the keyservers involved were intermittently throwing errors, although switching to the data= method for the key would probably have fixed that.

**Comment by christophermancini** [comment]
@jsmartin @TJC I updated the debian to not use the scripted repo install in favor of templated install instead. Tested on the vagrant cloud box "ubuntu/trusty64". I will circle back and update the RHEL repo install as well if you guys feel this is a better approach.

**Comment by christophermancini** [comment]
Also @jsmartin, unfortunately the security commands being pushed through riak-admin cli tool can't easily be made idempotent until the tool is updated to a parseable data format. We are actually going to have some new hires coming in soon complete this work. :)

**Comment by christophermancini** [comment]
Updated RHEL side to not dl remote script. Will merge this later today unless anyone has objections.

**Comment by mjbrender** [comment]
Wahoo! :+1:

**Comment by TJC** [comment]
Thanks!

**Comment by christophermancini** [comment]
Just an update, I am adding it back into Ansible Galaxy but encountered a known bug. I should have it straightened out within a few days.

**Pull request merged**
